### ISSUE TITLE
Could you tag and push tags on new versions?

### ISSUE THREAD

**Issue by mulkieran** [avakar/pytoml#19]
It makes packaging slightly easier for downstream.

**Comment by avakar** [comment]
Hi, I sure can. Can you tell me how those tags will be used? (I can tag regardless, I'm just curious.)

**Comment by mulkieran** [comment]
I _believe_ that it automates the generation of releases on GitHub, making it possible for downstream to specify location of version by release rather than commit tag.

**Comment by avakar** [comment]
I completely forgot about this issue, sorry, but I just release a new version and made a tag for it... Thanks!

**Comment by mulkieran** [comment]
Thanks!
