### ISSUE TITLE
dump() parameters are switched compared to json, pickle

### ISSUE THREAD

**Issue by takluyver** [avakar/pytoml#25]
pytoml looks like it's mirroring the API of modules like json and pickle, with `load[s]` and `dump[s]` methods. But whereas json and pickle have `dump(obj,  fd)`, pytoml has `dump(fd, obj)`.

Obviously fixing this would be a breaking API change, so maybe it's too late. But it's a minor annoyance.

**Comment by avakar** [comment]
Sorry for the late response.

Whoops. I'm going to break the api; I think consistency with json is more important.

**Comment by takluyver** [comment]
Thanks :-). Hopefully not too many people are relying on it yet.

**Comment by avakar** [comment]
Fixed in 0.1.12, upgrade with pip install --upgrade pytoml. Thanks!
