### ISSUE TITLE
Invalid floats such as nan included in output

### ISSUE THREAD

**Issue by mwilliamson-healx** [avakar/pytoml#27]
When the data includes a float such as `nan`, pytoml writes this out using `repr`. However, this isn't valid TOML, and indeed the parser raises an error when trying to parse it. Would it make more sense to raise an error in this situation?

**Comment by avakar** [comment]
Thanks for the issue! Yes, it would make more sense. I don't really have time to work on this, but if you want to submit a PR, it would be greatly appreciated.

**Comment by mwilliamson-healx** [comment]
Great! Did you have any thoughts on how to add tests that don't fit into the `toml-test` repository (say, to check the error message that gets spat out)? Left to my own devices, I'd add py.test.

**Comment by avakar** [comment]
py.tests seems fine, go nuts! :)

**Comment by avakar** [comment]
Released in 0.1.14.
