### ISSUE TITLE
table name with quoted strings fails to parse

### ISSUE THREAD

**Issue by dhuseby** [avakar/pytoml#28]
According to the toml spec, table names follow the same rules for keys which means they can be quoted. The following cases fail:
```
['bar']
[foo.'bar']
[foo.'bar'.baz]
```

**Comment by avakar** [comment]
Thanks for the issue. I will accept the associated PR once the review comments are addressed.

**Comment by raphlinus** [comment]
I have an updated PR for this, will upload shortly. It also handles the case where keys can be multiline literal strings (very rare in practice no doubt, but by my reading allowed by the spec).
