### ISSUE TITLE
Preceding '\n' at Table serialization

### ISSUE THREAD

**Issue by pari-** [avakar/pytoml#33]
Hi,

I wonder: what is: https://github.com/avakar/pytoml/blob/master/pytoml/writer.py#L123-L124 for? I recently started to use your library and I've been wondering (until I've been taking a peek into the source) how come that when using tables there's always an "unnecessary newline" prepended.

Knowing the "TOML"-spec, my initial guess was:

> (...) Tables (...) appear in square brackets _on a line by themselves_ (...)**[1]**

Yet, isn't this covered by all the appended '\n's in all calls to io.StringIO() [specifically assigned to 'fout' in pytoml's context]?

Thanks for your work and best regards,
Patrick

**[1]** - https://github.com/toml-lang/toml#table

**Comment by avakar** [comment]
It's there to insert an empty line between sections, i.e.

    [a]
    b = 2
                   # <- empty line here
    [c]
    d = 3

There is, however, a bug that may cause a spurious newline at the beginning of the output, which shouldn't be there. I'll fix that.

    >>> pytoml.dumps({'a': {'b': 2}, 'c': {'d': 3}})
    u'\n[a]\nb = 2\n\n[c]\nd = 3\n'

Is this what you were hinting at? What problems are the newlines causing you?

**Comment by avakar** [comment]
Fixed in 0.1.14.
