### ISSUE TITLE
Why is there another TOML parser?

### ISSUE THREAD

**Issue by thechief389** [avakar/pytoml#43]
There are currently two TOML parsers for Python. Can the two be merged?

**Comment by avakar** [comment]
There's actually more than two TOML parsers for Python.

> Can the two be merged?

Not really. How do you envision that would happen?

Anyway, if you're choosing a parser, you should use [uiri's][1].

  [1]: https://github.com/uiri/toml

**Comment by thechief389** [comment]
Thanks for helping me decide. I'm using uiri's.

**Comment by jdufresne** [comment]
If this project is no longer being maintained, I think it would benefit from a note in the README with a recommendation to use the alternative. Would you accept such a PR?
