### ISSUE TITLE
Encoder outputs invalid characters in key

### ISSUE THREAD

**Issue by jorisvr** [avakar/pytoml#49]
When I run

    pytoml.dump({u"\u00c0": 1}, sys.stdout)

it prints

    À = 1

which is not a valid TOML document. Bare keys must only contain ASCII characters.
A quoted string needs to be used, for example `"\u00c0" = 1`.

Similar case:

    pytoml.dump({u"\u00c0": { "a": 1}}, sys.stdout)

prints

    [À]
    a = 1

which is also invalid.

**Comment by avakar** [comment]
This is indeed a bug, thanks for the report!
