### ISSUE TITLE
Why not de-deprecate pytoml?

### ISSUE THREAD

**Issue by JulienPalard** [avakar/pytoml#59]
Hi! Your README states that pytoml is deprecated in favor of to toml package, yet I have less issues using pytoml than toml.

So, first of all thanks and congratulations \o/

Also what about removing the statement? It can mislead people towards a broken implementation, while yours is good.

**Comment by avakar** [comment]
Hi, thank you for the sentiment, I really do appreciate it.

The thing is, I have no plans on working on this project any further and as TOML adds more features, this project will get increasingly outdated. Unless someone else shows up and is willing to take ownership, people are better off basing their work on another implementation, even if you perceive it as more buggy.

Thanks again!
